In [1]:
import numpy as np;
a=np.array([3,5,6])
print("Two dimensional array:",a)

Two dimensional array: [3 5 6]


In [2]:
import numpy as np;
a=np.array([[3,4,5],[2,4,5]])
print("Three dimensional array:",a)

Three dimensional array: [[3 4 5]
 [2 4 5]]


In [3]:
import numpy as np;
e=np.zeros((4,5))
print("\n null array \n",e)


 null array 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np;
f=np.random.random((2,3))
print("\n Array with random value \n",f)


 Array with random value 
 [[0.4608406  0.09083434 0.20134835]
 [0.88420947 0.01079344 0.90822579]]


In [9]:
import numpy as np;
f=np.arange(0,8,1)
print("\n sequence value \n",f)


 sequence value 
 [0 1 2 3 4 5 6 7]


In [10]:
import numpy as np;
u=np.array([[3,2,4],[5,2,1]])
new=u.reshape((2,3))
print("Original array \n",u)
print("New reshaped array",new)

Original array 
 [[3 2 4]
 [5 2 1]]
New reshaped array [[3 2 4]
 [5 2 1]]
