#### INDEX RETRIEVAL

In [1]:
import numpy as np;
a=np.array([1,2,3,4,5,6])
x=np.where(a==4)
print(x)

(array([3]),)


In [3]:
import numpy as np;
a=np.array([1,6,2,7,6,4])
x=np.where((a/2)==0)
print(x)

(array([], dtype=int64),)


In [4]:
import numpy as np;
arr=np.array([0,1,2,3,7,8,9])
x=np.searchsorted(arr,8,side='left')
print(x)

5


#### `SORTING

In [5]:
import numpy as np;
a=np.sort([3,5,4,3,5])    #single dimensional
x=np.sort(a)
print(x)

[3 3 4 5 5]


In [7]:
import numpy as np;
a=np.array([[1,3,5,4],[4,3,2,6]])   #multi dimensional
x=np.sort(a)
print(x)

[[1 3 4 5]
 [2 3 4 6]]


#### BOOLEAN INDEXING

In [9]:
import numpy as np;
arr=np.array([31,78,69,100])
x=[False,True,False,True]
newarr=arr[x]
print(newarr)

[ 78 100]
