In [22]:
import numpy as np;##slicing
a=np.array([1,2,3,4,5,6,7,8,9])
slice=a[::2]
print(slice)

[1 3 5 7 9]


In [21]:
import numpy as np;
a=np.array([1,2,3,4,5,6,7,8,9])  ##slicing
slice1=a[2:6]
print(slice1)

[3 4 5 6]


In [23]:
import numpy as np;
b=np.array([1,5,6])
reverse=b[::-3]  ##reversing a array
print(reverse)

[6]


In [38]:
import numpy as np;
arr=np.array([[2,3,4],[4,4,5]]) #slicing multidimensional array
string=arr[0:2,:3]

print(string)

[[2 3 4]
 [4 4 5]]


In [27]:
import numpy as np;
arr=np.array([10,20,30,40]) #basic indexing
print(arr[0])

10


In [30]:
import numpy as np;
a=np.array([10,20,30,40]) #negative indexing
print(arr[-1])

40


In [32]:
import numpy as np;
b=np.array([6,7,4]) #slicing
print(arr[6:7:4])

[]


In [37]:
import numpy as np;
print(arr[0,11 2,1])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1954525625.py, line 3)

In [4]:
import numpy as np;
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
import numpy as np;
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
import numpy as np;
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [9]:
import numpy as np;
arr1=np.array([1,2,3,4,5,6])
result=np.split(arr1,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
import numpy as np;
arr=([1,2,3,4,5,6])
result=np.arr_split(arr,3)
print(result)

AttributeError: module 'numpy' has no attribute 'arr_split'