# ONE DIMENSIONAL ARRAY

In [1]:
import numpy as np;
a=np.array([2,3,4])
print("One dimensional array:",a)

One dimensional array: [2 3 4]


## TWO DIMENSIONAL ARRAY

In [2]:
import numpy as np;
b=np.array([[2,1,1],[2,2,3]])
print("Two dimensional array:",b)

Two dimensional array: [[2 1 1]
 [2 2 3]]


### THREE DIMENSIONAL ARRAY

In [3]:
import numpy as np;
c=np.array([[1,1,1],[2,2,3],[4,6,4]])
print("Three dimensional array:",c)

Three dimensional array: [[1 1 1]
 [2 2 3]
 [4 6 4]]


### CREATE ZERO ARRAY

In [4]:
import numpy as np;
print("\n zero array \n",np.zeros((2,3)))


 zero array 
 [[0. 0. 0.]
 [0. 0. 0.]]


### ARRAY WITH RANDOM VALUES

In [5]:
import numpy as np;
print("\n Random value \n",np.random.random((2,2)))


 Random value 
 [[0.48363061 0.99747922]
 [0.77453668 0.85269942]]


## IN STEP SEQUENCES

In [6]:
import numpy as np;
print("\n Sequence values \n",np.arange(0,20,1))


 Sequence values 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# RESHAPE THE ARRAY

In [7]:
import numpy as np;
f=np.array([[2,3,4],[5,4,3]])
print("Original array:\n",f)
print("\n Reshaped array:\n",f.reshape(3,2))

Original array:
 [[2 3 4]
 [5 4 3]]

 Reshaped array:
 [[2 3]
 [4 5]
 [4 3]]


# FLATTEN THE ARRAY

In [8]:
import numpy as np;
b=np.array([[3,2,4],[5,6,7]])
print("\n Original array \n",b)
print("\n Flattened array \n",b.flatten())


 Original array 
 [[3 2 4]
 [5 6 7]]

 Flattened array 
 [3 2 4 5 6 7]


# DIMENSION OF ARRAY

In [9]:
import numpy as np;
b=np.array([2,1,2])
print("Dimension of the array is \n",b.ndim)

Dimension of the array is 
 1


In [10]:
import numpy as np;
b=np.array([[2,1,1],[2,2,2]])
print("Dimension of the array is",b.ndim)

Dimension of the array is 2


In [11]:
import numpy as np;
b=np.array([[[2,3,2],[3,4,2]],[[2,3,2],[3,4,2]]])
print("Dimension of the array is",b.ndim)

Dimension of the array is 3


## SHAPE OF ARRAY

In [12]:
import numpy as np;
f=np.array([[4,3,2],[2,3,4]])
print("Shape of the array is",f.shape)

Shape of the array is (2, 3)


# DATA TYPE

In [18]:
import numpy as np;
g=np.array([[4,3,3],[4,5,2]])
print("Type is",g.dtype)

Type is int64


# LENGTH OF ARRAY

In [17]:
import numpy as np;
g=np.array([[2,3,4],[5,6,2]])
print("Maximum length is",len(g))

Maximum length is 2
