### Vector operations


In [2]:
import numpy as np;
arr1=np.array([10,20,30,40])
arr2=np.array([2,3,9,7])
print(arr1)                   #operations
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[10 20 30 40]
[2 3 9 7]
[12 23 39 47]
[ 8 17 21 33]
[ 20  60 270 280]
[5.         6.66666667 3.33333333 5.71428571]


In [7]:
import numpy as np;
a=np.array([1,2,3,4])      #scalar product
b=np.array([3,5,4,3])
print(a.dot(b))

37


In [10]:
import numpy as np;
a=np.array([[1,2],[18,28]])   #remainder
b=np.array([[4,5],[6,7]])
print(a%b)

[[1 2]
 [0 0]]


In [15]:
def my_fun(x,y):
    
    if x>y:
    
        return x-y
    else:
        
        return x+y
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
vect_fun=np.vectorize(my_fun)
print(vect_fun(a,b))

[3 5 7 9]
